version: '3.8'
services:
    frontend:
      container_name: frontend
      build: ./frontend
      volumes:
        - './:/app'
        - '/app/node_modules'
      ports:
        - 3000:3000
      stdin_open: true
      command: npm start